/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.workflow.jsonc --include-runtime=false --env-interface=ArticleWorkflowBindings workers/article-workflow/worker-configuration.d.ts` (hash: d6f889bb16e5098352ab7ded0a720fe9)
interface __BaseEnv_ArticleWorkflowBindings {
	ARTICLE_ASSETS: R2Bucket;
	GEMINI_TEXT_MODEL: "gemini-2.5-flash";
	GEMINI_IMAGE_MODEL: "gemini-3.1-flash-image-preview";
	DEEPSEEK_TEXT_MODEL: "deepseek-chat";
	DATABASE_URL: string;
	GEMINI_API_KEY: string;
	AI_CREDENTIAL_KEYRING: string;
	AI_CREDENTIAL_ACTIVE_KEY_ID: string;
	ARTICLE_JOBS: Workflow<Parameters<import("./index").ArticleJobsWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ArticleWorkflowBindings {}
}
interface ArticleWorkflowBindings extends __BaseEnv_ArticleWorkflowBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_TEXT_MODEL" | "GEMINI_IMAGE_MODEL" | "DEEPSEEK_TEXT_MODEL" | "DATABASE_URL" | "GEMINI_API_KEY" | "AI_CREDENTIAL_KEYRING" | "AI_CREDENTIAL_ACTIVE_KEY_ID">> {}
}
