/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.workflow.jsonc --include-runtime=false --env-interface=ArticleWorkflowBindings workers/article-workflow/worker-configuration.d.ts` (hash: 05ffd420947946a1918addde42f70add)
interface __BaseEnv_ArticleWorkflowBindings {
	ARTICLE_ASSETS: R2Bucket;
	DATABASE_URL: string;
	GEMINI_API_KEY: string;
	ARTICLE_JOBS: Workflow<Parameters<import("./index").ArticleJobsWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ArticleWorkflowBindings {}
}
interface ArticleWorkflowBindings extends __BaseEnv_ArticleWorkflowBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "GEMINI_API_KEY">> {}
}
