export {
  beginGenerationRevision,
  createDeckProject,
  createRenderAsset,
  createSlide,
  deleteDeckProject,
  deleteSlide,
  getCaptions,
  getCurrentRevisionContext,
  getDeckProject,
  getDeckWithAssets,
  getRenderAssets,
  listDeckProjects,
  listSlidesForImageGeneration,
  markDeckStatus,
  markSlideImageFailed,
  markSlideImageGenerated,
  markSlidesImagePending,
  parseRevisionNumber,
  replaceGeneratedContent,
  reorderSlides,
  updateDeckProject,
  updateSlide,
} from '@/server/modules/articles/service';
